BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "zybo"
BBFILE_PATTERN_zybo = "^${LAYERDIR}/"
BBFILE_PRIORITY_zybo = "6"

LAYERSERIES_COMPAT_zybo = "scarthgap"
LAYERDEPENDS_zybo = "core xilinx"
