BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "custom-projects"
BBFILE_PATTERN_zybo = "^${LAYERDIR}/"
BBFILE_PRIORITY_zybo = "6"
