BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "custom-projects"
LAYERSERIES_COMPAT_custom-projects = "scarthgap"
BBFILE_PATTERN_custom-projects = "^${LAYERDIR}/"
BBFILE_PRIORITY_custom-projects = "6"
